// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0KKM-Dm-7wOk-S3zLkBAjMn8Z4JL9snA',
    appId: '1:547950781924:web:7511c8e2cc79e2cc28d3f1',
    messagingSenderId: '547950781924',
    projectId: 'faskhaninja',
    authDomain: 'faskhaninja.firebaseapp.com',
    storageBucket: 'faskhaninja.appspot.com',
    measurementId: 'G-2BN39RQZDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByq-Wz6EZXITTN_E-TbtclqdhbsOKXt2Y',
    appId: '1:547950781924:android:34cabc1101a4498b28d3f1',
    messagingSenderId: '547950781924',
    projectId: 'faskhaninja',
    storageBucket: 'faskhaninja.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsyMyPXy6aX7a7EbJoMnkjlFirdpkUfJ0',
    appId: '1:547950781924:ios:919f0bbfb60b0c0e28d3f1',
    messagingSenderId: '547950781924',
    projectId: 'faskhaninja',
    storageBucket: 'faskhaninja.appspot.com',
    iosBundleId: 'com.smartvision.faskhaninjaVendor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsyMyPXy6aX7a7EbJoMnkjlFirdpkUfJ0',
    appId: '1:547950781924:ios:919f0bbfb60b0c0e28d3f1',
    messagingSenderId: '547950781924',
    projectId: 'faskhaninja',
    storageBucket: 'faskhaninja.appspot.com',
    iosBundleId: 'com.smartvision.faskhaninjaVendor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0KKM-Dm-7wOk-S3zLkBAjMn8Z4JL9snA',
    appId: '1:547950781924:web:367886d678bad9d128d3f1',
    messagingSenderId: '547950781924',
    projectId: 'faskhaninja',
    authDomain: 'faskhaninja.firebaseapp.com',
    storageBucket: 'faskhaninja.appspot.com',
    measurementId: 'G-TXNVHSHD1T',
  );
}
